### ISSUE TITLE
About creating the lists 

### ISSUE THREAD

**Issue by siddupp** [lochenchou/DORN_radar#9]
Sir I have downloaded the nuscenes dataset but those have different sequence than you mentioned in the lists so I wanted to generate lists  files for them how can i do it please suggest me the solution. thank you waiting for the response...

The error is this 
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/nuscenes/v1.0-trainval/samples/CAM_FRONT/n008-2018-09-18-12-53-31-0400__CAM_FRONT__1537289751512404.jpg'

but i have dataset of this 
![Screenshot from 2022-11-23 11-52-52](https://user-images.githubusercontent.com/59868895/203483834-b1f94973-8394-4405-8679-3721bfe3432a.png)

**Comment by lochenchou** [comment]
Hi,
I think the issue is due to the difference of the directory structure.
